site_name: Samenvatting Jef Rpg
nav:
    - Home: 'index.md'
    - 'Rpg':
        - 'Informatie': 'rpg.md'
        - 'Example': 'rpgExample.md'
    - Jef:
        - 'View only': 'jefViewOnly.md'
        - 'Create Update Edit Delete': 'jefCrud.md'
theme:
  name: cosmo
  palette:
      primary: light green
      scheme: slate
      accent: orange
  icon:
    logo: octicons/squirrel-16
